import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillYoutube, AiFillGithub } from 'react-icons/ai'
import Image from 'next/image';
import ahmed from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import { useState } from "react"
import React, { useRef } from 'react';
import emailjs, { send } from '@emailjs/browser';
import ReactDOM from 'react-dom/client';
export default function Home() {
  const form = useRef();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs.sendForm('service_h7fzmal', 'template_m1z3t8e', form.current, 'q0IXpqqSiAO654zyC')
      .then((result) => {
        console.log(result.text);
      }, (error) => {
        console.log(error.text);
      });
  }
  const [darkMode, setDarkMode] = useState(false);
  function Football() {
    alert("Your message sended!");
  };
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>AhmedAkyol</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:pd-40 dark:bg-gray-800'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-teal-600'>AhmedAkyol</h1>
            <ul className='flex items-center'>
            </ul>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer' />
            </li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='https://drive.google.com/file/d/1CXsX-ZSxRWH6QVnX1xh-cR2xK5tJBDhX/view?usp=sharing'>Resume</a></li>
          </nav>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96'>
            <Image src={ahmed} layout="fill" objectFit='cover' />
          </div>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Ahmed Akyol</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-8 dark:text-white'>I developed myself on electrical and electronic systems at Sabiha Gökçen Vocational and Technical Anatolian High School, where I started my education in 2016. Along with the projects I later worked on, I also developed myself in software and gained experience in .Net Systems and Web-based applications in this process. In addition, I continued to develop myself in languages such as C#, Javascript and SQL with the projects I developed individually.
              During these processes, I also improved myself on topics that every software developer should know, such as Clean Code and Design Patterns.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-teal-600'>
            <a href='http://bit.ly/3Kl45wx'><AiFillLinkedin className='cursor-pointer' /></a>
            <a href='https://github.com/llakyoll'><AiFillGithub className='cursor-pointer' /></a>
            <a href='https://www.youtube.com/channel/UCnLwxu_wdbvXQjFjaegIVgw'><AiFillYoutube className='cursor-pointer' /></a>
          </div>
        </section>
        {/* Second Page */}
        <section>
          <div>
            <h3 className='text-3xl py-1 text-center dark:text-teal-600'>Services I offer</h3>
            <p className='text-md py-5 leading-8 text-gray-8 md:text-xl max-w-xl mx-auto dark:text-white'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas erat lorem, luctus sit amet felis iaculis, pellentesque pharetra tortor. In sed nisi arcu. Duis in tincidunt massa,
                quis blandit nibh. Etiam feugiat odio nec nunc posuere ultrices. Phasellus finibus interdum justo a scelerisque. Mauris et efficitur tortor. Pellentesque cursus vestibulum lectus.
                Maecenas eu purus viverra, condimentum eros a, cursus ipsum.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:text-white'>
              <Image class="mx-auto" src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Design</h3>
              <p className='py-2'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas erat lorem, luctus sit amet felis iaculis, pellentesque pharetra tortor. In sed nisi arcu. Duis in tincidunt massa,
                quis blandit nibh. Etiam feugiat odio nec nunc posuere ultrices. Phasellus finibus interdum justo a scelerisque. Mauris et efficitur tortor. Pellentesque cursus vestibulum lectus.
                Maecenas eu purus viverra, condimentum eros a, cursus ipsum.
              </p>
              <h3 className='py-4 text-teal-600'>Design Tool I Use</h3>
              <p className='text-gray-800 py-1 dark:text-white '>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Fİgma</p>
              <p className='text-gray-800 py-1 dark:text-white'>Illustrator</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:text-white'>
              <Image class="mx-auto" src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 '>Popular Software Languages</h3>
              <p className='py-2'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas erat lorem, luctus sit amet felis iaculis, pellentesque pharetra tortor. In sed nisi arcu. Duis in tincidunt massa,
                quis blandit nibh. Etiam feugiat odio nec nunc posuere ultrices. Phasellus finibus interdum justo a scelerisque. Mauris et efficitur tortor. Pellentesque cursus vestibulum lectus.
                Maecenas eu purus viverra, condimentum eros a, cursus ipsum.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-white">
              <Image class="mx-auto" src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Happy Costumers</h3>
              <p className='py-2'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas erat lorem, luctus sit amet felis iaculis, pellentesque pharetra tortor. In sed nisi arcu. Duis in tincidunt massa,
                quis blandit nibh. Etiam feugiat odio nec nunc posuere ultrices. Phasellus finibus interdum justo a scelerisque. Mauris et efficitur tortor. Pellentesque cursus vestibulum lectus.
                Maecenas eu purus viverra, condimentum eros a, cursus ipsum.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-teal-500'>Portfolio</h3>
            <p className='py-2 dark:text-white'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas erat lorem, luctus sit amet felis iaculis, pellentesque pharetra tortor. In sed nisi arcu. Duis in tincidunt massa,
              quis blandit nibh. Etiam feugiat odio nec nunc posuere ultrices. Phasellus finibus interdum justo a scelerisque. Mauris et efficitur tortor. Pellentesque cursus vestibulum lectus.
              Maecenas eu purus viverra, condimentum eros a, cursus ipsum.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
        <section>
          <div className='flex' class="container" width={100} height={100}>
            <form className='bg-white flex flex-col py-2 w-11/12 max-w-2xl rounded-xl dark:bg-gray-800' ref={form} onSubmit={sendEmail}>
              <h1 className='text-xl font-burtons dark:text-teal-600 p-4 dark:bg-gray-700'>Contact With Me</h1>
              <input className='border-0 mt-2.5 mb-0 p-5 outline-0 bg-white text-base dark:bg-gray-700' type="text" name="user_name" placeholder='Your Name' required></input>
              <input className='border-0 mt-2.5 mb-0 p-5 outline-0 bg-white text-base dark:bg-gray-700' type="email" name="user_email" placeholder='E-mail' required></input>
              <input className='border-0 mt-2.5 mb-0 p-5 outline-0 bg-white text-base dark:bg-gray-700' type="text" name='user_phone' placeholder='Phone Number' required></input>
              <textarea className='border-0 mt-2.5 mb-0 p-5 outline-0 bg-white text-base dark:bg-gray-700' name="message" rows={4} placeholder="How can i help you?" required></textarea>
              <button onClick={Football} className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white w-20 px-4 py-2 rounded-md mt-2' type='submit'>Send</button>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
}
